In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import warnings
warnings.filterwarnings("ignore")

In [4]:
train_df = pd.read_csv("data/zion_training_data.csv")
train_df.head()

ID     Location Mode_of_delivery  Calls_to_customer_care  \
0  5083   Gachibowli             Auto                       3   
1   158  Hitech City             Bike                       3   
2  7861   Gachibowli             Bike                       4   
3  3592   Khairtabad             Bike                       2   
4  2718  Hitech City              Car                       4   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0                 1.0         241.5              3.0                  M   
1                 2.0         304.5              2.0                  F   
2                 NaN         208.5              3.0                  M   
3                 3.0         201.0             10.0                  F   
4                 5.0         238.5              3.0                  M   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0                 9                   4865                1  
1                39                   3845                1  
2                10                   4648                0  
3                 1                   5632                0  
4                 2                   1048                1

In [5]:
train_df.describe()

ID  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
count   5774.000000             5774.000000         4310.000000   5774.000000   
mean    5461.922757                4.036543            3.025522    315.113526   
std     3171.024555                1.130747            1.404597     71.674514   
min        2.000000                2.000000            1.000000    144.000000   
25%     2701.500000                3.000000            2.000000    255.000000   
50%     5458.000000                4.000000            3.000000    321.000000   
75%     8186.750000                5.000000            4.000000    376.500000   
max    10998.000000                7.000000            5.000000    465.000000   

       Prior_purchases  Discount_offered  Weight_of_food_in_gms  \
count      4906.000000       5774.000000            5774.000000   
mean          3.574603         13.519744            3647.108763   
std           1.532069         16.349557            1630.353573   
min           2.000000          1.000000            1001.000000   
25%           3.000000          4.000000            1851.250000   
50%           3.000000          7.000000            4148.500000   
75%           4.000000         10.000000            5068.000000   
max          10.000000         65.000000            7846.000000   

       Reached_on_time  
count      5774.000000  
mean          0.597679  
std           0.490408  
min           0.000000  
25%           0.000000  
50%           1.000000  
75%           1.000000  
max           1.000000

In [8]:
test_df = pd.read_csv("data/zion_test_data.csv")
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2475 non-null   int64  
 1   Location                2475 non-null   object 
 2   Mode_of_delivery        2475 non-null   object 
 3   Calls_to_customer_care  2475 non-null   int64  
 4   Rating_of_customer      1867 non-null   float64
 5   Cost_of_food            2475 non-null   float64
 6   Prior_purchases         2098 non-null   float64
 7   Gender_of_customer      2475 non-null   object 
 8   Discount_offered        2475 non-null   int64  
 9   Weight_of_food_in_gms   2475 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 193.5+ KB


EDA

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5774 entries, 0 to 5773
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      5774 non-null   int64  
 1   Location                5774 non-null   object 
 2   Mode_of_delivery        5774 non-null   object 
 3   Calls_to_customer_care  5774 non-null   int64  
 4   Rating_of_customer      4310 non-null   float64
 5   Cost_of_food            5774 non-null   float64
 6   Prior_purchases         4906 non-null   float64
 7   Gender_of_customer      5774 non-null   object 
 8   Discount_offered        5774 non-null   int64  
 9   Weight_of_food_in_gms   5774 non-null   int64  
 10  Reached_on_time         5774 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 496.3+ KB


In [10]:
train_df.Location.value_counts() # one-hot encoding

Hitech City     1901
Secunderabad     993
Masab Tank       983
Khairtabad       959
Gachibowli       938
Name: Location, dtype: int64

In [11]:
train_df.Mode_of_delivery.value_counts() # doing label encoding since bike is faster than auto and auto is faster than car

Bike    3927
Car      933
Auto     914
Name: Mode_of_delivery, dtype: int64

In [12]:
train_df.Calls_to_customer_care.describe() # remove outliers

count    5774.000000
mean        4.036543
std         1.130747
min         2.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Calls_to_customer_care, dtype: float64

In [13]:
train_df.Rating_of_customer.describe() # remove outliers; fill missing value using median and then using model based

count    4310.000000
mean        3.025522
std         1.404597
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Rating_of_customer, dtype: float64

In [14]:
train_df.Cost_of_food.describe() # remove outliers;

count    5774.000000
mean      315.113526
std        71.674514
min       144.000000
25%       255.000000
50%       321.000000
75%       376.500000
max       465.000000
Name: Cost_of_food, dtype: float64

In [15]:
train_df.Prior_purchases.describe() # remove outliers; fill missing value using median and then using model based

count    4906.000000
mean        3.574603
std         1.532069
min         2.000000
25%         3.000000
50%         3.000000
75%         4.000000
max        10.000000
Name: Prior_purchases, dtype: float64

In [16]:
train_df.Gender_of_customer.value_counts()

F    2912
M    2862
Name: Gender_of_customer, dtype: int64

In [17]:
train_df.Discount_offered.describe() # remove outliers;

count    5774.000000
mean       13.519744
std        16.349557
min         1.000000
25%         4.000000
50%         7.000000
75%        10.000000
max        65.000000
Name: Discount_offered, dtype: float64

In [18]:

train_df.Weight_of_food_in_gms.describe() # remove outliers;

count    5774.000000
mean     3647.108763
std      1630.353573
min      1001.000000
25%      1851.250000
50%      4148.500000
75%      5068.000000
max      7846.000000
Name: Weight_of_food_in_gms, dtype: float64

In [19]:
train_df.Reached_on_time.value_counts()

1    3451
0    2323
Name: Reached_on_time, dtype: int64

**Handling missing values**

In [20]:
# Rating_of_customer, Prior_purchases
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5774 entries, 0 to 5773
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      5774 non-null   int64  
 1   Location                5774 non-null   object 
 2   Mode_of_delivery        5774 non-null   object 
 3   Calls_to_customer_care  5774 non-null   int64  
 4   Rating_of_customer      4310 non-null   float64
 5   Cost_of_food            5774 non-null   float64
 6   Prior_purchases         4906 non-null   float64
 7   Gender_of_customer      5774 non-null   object 
 8   Discount_offered        5774 non-null   int64  
 9   Weight_of_food_in_gms   5774 non-null   int64  
 10  Reached_on_time         5774 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 496.3+ KB


In [21]:
missing_cols_matadata = train_df[['Rating_of_customer', 'Prior_purchases']].median()
train_df[['Rating_of_customer', 'Prior_purchases']] = train_df[['Rating_of_customer', 'Prior_purchases']].fillna(missing_cols_matadata)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5774 entries, 0 to 5773
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      5774 non-null   int64  
 1   Location                5774 non-null   object 
 2   Mode_of_delivery        5774 non-null   object 
 3   Calls_to_customer_care  5774 non-null   int64  
 4   Rating_of_customer      5774 non-null   float64
 5   Cost_of_food            5774 non-null   float64
 6   Prior_purchases         5774 non-null   float64
 7   Gender_of_customer      5774 non-null   object 
 8   Discount_offered        5774 non-null   int64  
 9   Weight_of_food_in_gms   5774 non-null   int64  
 10  Reached_on_time         5774 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 496.3+ KB


Handling Categories

In [22]:
train_df['Mode_of_delivery'] = train_df.Mode_of_delivery.replace({'Bike': 3, 'Auto':2, 'Car':1}) 
train_df['Mode_of_delivery'].value_counts()

3    3927
1     933
2     914
Name: Mode_of_delivery, dtype: int64

**Handling Numerical**

In [23]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5774 entries, 0 to 5773
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      5774 non-null   int64  
 1   Location                5774 non-null   object 
 2   Mode_of_delivery        5774 non-null   int64  
 3   Calls_to_customer_care  5774 non-null   int64  
 4   Rating_of_customer      5774 non-null   float64
 5   Cost_of_food            5774 non-null   float64
 6   Prior_purchases         5774 non-null   float64
 7   Gender_of_customer      5774 non-null   object 
 8   Discount_offered        5774 non-null   int64  
 9   Weight_of_food_in_gms   5774 non-null   int64  
 10  Reached_on_time         5774 non-null   int64  
dtypes: float64(3), int64(6), object(2)
memory usage: 496.3+ KB


In [24]:
num_feat = ['Mode_of_delivery', 'Calls_to_customer_care', 'Rating_of_customer', 'Cost_of_food', 'Prior_purchases', 'Discount_offered', 'Weight_of_food_in_gms']


In [25]:
# train_df = train_df_orig
train_df.head(1)

ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0  5083  Gachibowli                 2                       3   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0                 1.0         241.5              3.0                  M   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0                 9                   4865                1

In [26]:
# remove outliers
from scipy import stats
print(train_df.shape)
train_df_orig = train_df.copy()
train_df = train_df[(np.abs(stats.zscore(train_df[num_feat])) < 3).all(axis=1)]
print(train_df.shape)

(5774, 11)
(5562, 11)


In [27]:
enc = OneHotEncoder(handle_unknown='ignore', drop = 'first')
cat_cols = ['Location', 'Gender_of_customer']

enc.fit(train_df[cat_cols])
print(enc.categories_)

cat_feat = enc.transform(train_df[cat_cols]).toarray()
print(cat_feat)

cat_df = pd.DataFrame(cat_feat)
print(cat_df.shape)
cat_df.head(1)

[array(['Gachibowli', 'Hitech City', 'Khairtabad', 'Masab Tank',
       'Secunderabad'], dtype=object), array(['F', 'M'], dtype=object)]
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]]
(5562, 5)


0    1    2    3    4
0  0.0  0.0  0.0  0.0  1.0

In [28]:
train_df[num_feat].describe()

Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  \
count       5562.000000             5562.000000         5562.000000   
mean           2.516181                4.046386            3.016721   
std            0.757987                1.135650            1.213383   
min            1.000000                2.000000            1.000000   
25%            2.000000                3.000000            2.000000   
50%            3.000000                4.000000            3.000000   
75%            3.000000                5.000000            4.000000   
max            3.000000                7.000000            5.000000   

       Cost_of_food  Prior_purchases  Discount_offered  Weight_of_food_in_gms  
count   5562.000000       5562.00000       5562.000000            5562.000000  
mean     315.721413          3.34502         12.923768            3649.212154  
std       71.673454          1.10262         15.490956            1634.964997  
min      144.000000          2.00000          1.000000            1001.000000  
25%      255.000000          3.00000          4.000000            1841.000000  
50%      322.500000          3.00000          7.000000            4155.500000  
75%      376.500000          4.00000         10.000000            5069.750000  
max      465.000000          7.00000         62.000000            7846.000000

In [29]:
# scaling
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

train_df[num_feat] = ss.fit_transform(train_df[num_feat])

train_df[num_feat].describe()

Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  \
count      5.562000e+03            5.562000e+03        5.562000e+03   
mean      -1.507444e-16            3.768610e-17        1.290270e-16   
std        1.000090e+00            1.000090e+00        1.000090e+00   
min       -2.000452e+00           -1.802113e+00       -1.662214e+00   
25%       -6.810505e-01           -9.214810e-01       -8.379979e-01   
50%        6.383514e-01           -4.084916e-02       -1.378140e-02   
75%        6.383514e-01            8.397827e-01        8.104351e-01   
max        6.383514e-01            2.601046e+00        1.634652e+00   

       Cost_of_food  Prior_purchases  Discount_offered  Weight_of_food_in_gms  
count  5.562000e+03     5.562000e+03      5.562000e+03           5.562000e+03  
mean  -1.729409e-16     1.111421e-16      6.579099e-17           1.788493e-17  
std    1.000090e+00     1.000090e+00      1.000090e+00           1.000090e+00  
min   -2.396101e+00    -1.219949e+00     -7.697937e-01          -1.619882e+00  
25%   -8.472715e-01    -3.129371e-01     -5.761149e-01          -1.106063e+00  
50%    9.458448e-02    -3.129371e-01     -3.824361e-01           3.096906e-01  
75%    8.480692e-01     5.940749e-01     -1.887573e-01           8.689272e-01  
max    2.082947e+00     3.315111e+00      3.168342e+00           2.567128e+00

In [30]:
print(train_df.shape)
train_df.head(1)

(5562, 11)


ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0  5083  Gachibowli          -0.68105               -0.921481   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0           -1.662214     -1.035643        -0.312937                  M   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0         -0.253317               0.743684                1

In [31]:
from sklearn.decomposition import PCA
pca = PCA(n_components=7, svd_solver='full')
pca.fit(train_df[num_feat])
print(pca.explained_variance_ratio_)

[0.24321339 0.1929876  0.14407432 0.14149472 0.11944066 0.09503284
 0.06375648]


In [32]:
print(train_df[num_feat].shape, cat_df.shape)
x_train = pd.concat([train_df[num_feat].reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)
print(x_train.shape)
x_train.head(1)

(5562, 7) (5562, 5)
(5562, 12)


Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
0          -0.68105               -0.921481           -1.662214     -1.035643   

   Prior_purchases  Discount_offered  Weight_of_food_in_gms    0    1    2  \
0        -0.312937         -0.253317               0.743684  0.0  0.0  0.0   

     3    4  
0  0.0  1.0

In [33]:
y_train = train_df.Reached_on_time
print(y_train.shape)

(5562,)


Modelling

When we want to use any model, just run that specific modelling cell one, not the other models.

In [34]:
# Grid search cross validation
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

parameters = [{'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']},
              {'penalty':['none', 'l2', 'l1', 'elasticnet']},
              {'C':[0.001, 0.01, 0.1, 1, 10, 100]}]



grid_search = GridSearchCV(estimator = logreg,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           verbose=0)


grid_search.fit(x_train, y_train)

print("tuned hpyerparameters :(best parameters) ",grid_search.best_params_)
print("accuracy :",grid_search.best_score_)

tuned hpyerparameters :(best parameters)  {'solver': 'newton-cg'}
accuracy : 0.641314711034407


In [35]:
logreg = LogisticRegression(**grid_search.best_params_)
logreg.fit(x_train, y_train)
logreg

LogisticRegression(solver='newton-cg')

SVM

In [36]:
# from sklearn.svm import SVC
# # defining parameter range
# param_grid = {'C': [0.1, 1, 10, 100, 1000], 
#               'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
#               'kernel': ['rbf']} 
  
# grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# # fitting the model for grid search
# grid.fit(x_train, y_train)


# # print best parameter after tuning
# print(grid.best_params_)
  
# # print how our model looks after hyper-parameter tuning
# print(grid.best_estimator_)

KNN

In [37]:
# from sklearn.neighbors import KNeighborsClassifier

# k_range = list(range(1, 31))
# print(k_range)

# param_grid = dict(n_neighbors=k_range)
# print(param_grid)

# knn = knn = KNeighborsClassifier()

# grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False)
# grid.fit(x_train, y_train)


# # print best parameter after tuning
# print(grid.best_params_)
  
# # print how our model looks after hyper-parameter tuning
# print(grid.best_estimator_)

Random Forest

In [38]:
# Final Model-1: 
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=42)

param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [1],
    'criterion' :['gini', 'entropy']
}

grid = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5, verbose = 3)
grid.fit(x_train, y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=200;, score=0.593 total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=200;, score=0.593 total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=200;, score=0.594 total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=200;, score=0.593 total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=200;, score=0.593 total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=500;, score=0.593 total time=   1.3s
[CV 2/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=500;, score=0.593 total time=   1.3s
[CV 3/5] END criterion=gini, max_depth=1, max_features=auto, n_estimators=500;, score=0.594 total time=   1.3s
[CV 4/5] END criterion=gini, max_depth=1, max_featu

In [41]:
# Final Model-1: 
from sklearn.ensemble import RandomForestClassifier
# rfc=RandomForestClassifier(**{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 500}, random_state=42)

rfc = RandomForestClassifier(max_depth=1, n_estimators=200, random_state=42)

rfc.fit(x_train, y_train)

RandomForestClassifier(max_depth=1, n_estimators=200, random_state=42)

Naive Bayes

In [40]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

Decision Tree

In [43]:
# Final Model-2
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : [5, 6, 7, 8, 9],
              'criterion' :['gini', 'entropy']
             }
tree_clas = DecisionTreeClassifier(random_state=1024)
grid = GridSearchCV(estimator=tree_clas, param_grid=param_grid, cv=5, verbose=True)
grid.fit(x_train, y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

Fitting 5 folds for each of 90 candidates, totalling 450 fits
{'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 8, 'max_features': 'auto'}
DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=8,
                       max_features='auto', random_state=1024)


**Submission File**

In [42]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2475 non-null   int64  
 1   Location                2475 non-null   object 
 2   Mode_of_delivery        2475 non-null   object 
 3   Calls_to_customer_care  2475 non-null   int64  
 4   Rating_of_customer      1867 non-null   float64
 5   Cost_of_food            2475 non-null   float64
 6   Prior_purchases         2098 non-null   float64
 7   Gender_of_customer      2475 non-null   object 
 8   Discount_offered        2475 non-null   int64  
 9   Weight_of_food_in_gms   2475 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 193.5+ KB


In [44]:
test_df[['Rating_of_customer', 'Prior_purchases']] = test_df[['Rating_of_customer', 'Prior_purchases']].fillna(missing_cols_matadata)

In [45]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2475 non-null   int64  
 1   Location                2475 non-null   object 
 2   Mode_of_delivery        2475 non-null   object 
 3   Calls_to_customer_care  2475 non-null   int64  
 4   Rating_of_customer      2475 non-null   float64
 5   Cost_of_food            2475 non-null   float64
 6   Prior_purchases         2475 non-null   float64
 7   Gender_of_customer      2475 non-null   object 
 8   Discount_offered        2475 non-null   int64  
 9   Weight_of_food_in_gms   2475 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 193.5+ KB


In [46]:
print(cat_cols)
print(num_feat)

['Location', 'Gender_of_customer']
['Mode_of_delivery', 'Calls_to_customer_care', 'Rating_of_customer', 'Cost_of_food', 'Prior_purchases', 'Discount_offered', 'Weight_of_food_in_gms']


In [47]:
test_df['Mode_of_delivery'] = test_df.Mode_of_delivery.replace({'Bike': 3, 'Auto':2, 'Car':1}) 
test_df['Mode_of_delivery'].value_counts()

3    1664
2     412
1     399
Name: Mode_of_delivery, dtype: int64

In [48]:
test_df[num_feat] = ss.transform(test_df[num_feat])

In [49]:
cat_feat_test = enc.transform(test_df[cat_cols]).toarray()
print(cat_feat_test)

cat_df_test = pd.DataFrame(cat_feat_test)
print(cat_df_test.shape)
cat_df_test.head(1)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2475, 5)


0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0

In [50]:
print(test_df[num_feat].shape, cat_df_test.shape)
x_test = pd.concat([test_df[num_feat].reset_index(drop=True), cat_df_test.reset_index(drop=True)], axis=1)
print(x_test.shape)
x_test.head(1)

(2475, 7) (2475, 5)
(2475, 12)


Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
0          -0.68105               -0.040849           -0.837998     -0.700761   

   Prior_purchases  Discount_offered  Weight_of_food_in_gms    0    1    2  \
0        -0.312937          2.006269               -1.47797  0.0  0.0  0.0   

     3    4  
0  0.0  0.0

In [51]:
test_df['Reached_on_time'] = rfc.predict(x_test).astype('int')
test_df.head(2)

ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0   1  Gachibowli          -0.68105               -0.040849   
1   4  Khairtabad          -0.68105               -0.921481   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0           -0.837998     -0.700761        -0.312937                  F   
1           -0.013781     -0.721691         0.594075                  M   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0          2.006269              -1.477970                1  
1         -0.188757              -1.512225                1

In [55]:
soln_df = pd.read_csv("data/zion_solution.csv")
soln_df.head()

ID  Reached_on_time
0   1                1
1   4                1
2   6                1
3   8                1
4  10                1

In [56]:
mdf = pd.merge(test_df[['ID', 'Reached_on_time']].rename(columns={"Reached_on_time": "Reached_on_time_pred"}), soln_df, on='ID', how='left')
mdf.head()

ID  Reached_on_time_pred  Reached_on_time
0   1                     1                1
1   4                     1                1
2   6                     1                1
3   8                     1                1
4  10                     1                1

In [58]:
from sklearn.metrics import classification_report
print(classification_report(mdf.Reached_on_time, mdf.Reached_on_time_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1003
           1       0.59      1.00      0.75      1472

    accuracy                           0.59      2475
   macro avg       0.30      0.50      0.37      2475
weighted avg       0.35      0.59      0.44      2475



In [67]:
# x_train.head()
# x_train.to_csv("x_train.csv", index=False)

# y_train.head()
# y_train.to_csv("y_train.csv", index=False)

# x_test.head()
# x_test.to_csv("x_test.csv", index=False)

y_test = mdf.Reached_on_time.copy()
y_test.head()
y_test.to_csv("y_test.csv", index=False)


In [66]:
y_test.value_counts()

1    1472
0    1003
Name: Reached_on_time, dtype: int64

In [53]:
# test_df[['ID', 'Reached_on_time']].to_csv("submission_rf.csv", index=False)

**Solution Document**

**Why did I choose the Random Forest model as Final Model?**
- I was getting best cross-validation score and public leader board score, so I chose this model becase it has least generalisation error among the tried models. 
- Random Forest reduced variance from Decision Tree Model which makes it more robust. 
- Logistic regression model was the baseline model and other models were not performing very well on leaderboard.

**Suggestions to Zion Restaurants:**

In [ ]:
from sklearn.tree import _tree

def tree_to_code(tree, feature_names):
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]
    print("def tree({}):".format(", ".join(feature_names)))

    def recurse(node, depth):
        indent = "  " * depth
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            print("{}if {} <= {}:".format(indent, name, threshold))
            recurse(tree_.children_left[node], depth + 1)
            print("{}else:  # if {} > {}".format(indent, name, threshold))
            recurse(tree_.children_right[node], depth + 1)
        else:
            print("{}return {}".format(indent, tree_.value[node]))

    recurse(0, 1)

dt = DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=8,
                       max_features='auto', random_state=1024)


train_df_exp = train_df.copy()
train_df_exp[num_feat] = ss.inverse_transform(train_df_exp[num_feat])
x_train_exp = pd.concat([train_df_exp[num_feat].reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)
x_train_exp = x_train_exp.rename({0: 'Gachibowli', 1:'Secunderabad', 2:'Masab Tank', 3:'Khairtabad', 4:'Female'}, axis=1)

dt.fit(x_train_exp, y_train)
tree_to_code(dt, x_train_exp.columns)

def tree(Mode_of_delivery, Calls_to_customer_care, Rating_of_customer, Cost_of_food, Prior_purchases, Discount_offered, Weight_of_food_in_gms, Gachibowli, Secunderabad, Masab Tank, Khairtabad, Female):
  if Discount_offered <= 10.5:
    if Prior_purchases <= 2.5:
      if Rating_of_customer <= 3.5:
        if Weight_of_food_in_gms <= 4025.0:
          return [[23. 78.]]
        else:  # if Weight_of_food_in_gms > 4025.0
          return [[428. 289.]]
      else:  # if Rating_of_customer > 3.5
        return [[193. 140.]]
    else:  # if Prior_purchases > 2.5
      if Weight_of_food_in_gms <= 4018.5:
        if Discount_offered <= 5.5:
          if Weight_of_food_in_gms <= 1987.0:
            if Calls_to_customer_care <= 3.5:
              if Cost_of_food <= 264.75:
                return [[ 4. 30.]]
              else:  # if Cost_of_food > 264.75
                return [[12.  6.]]
            else:  # if Calls_to_customer_care > 3.5
              return [[327. 346.]]
          else:  #

```python
def tree(Mode_of_delivery, Calls_to_customer_care, Rating_of_customer, Cost_of_food, Prior_purchases, Discount_offered, Weight_of_food_in_gms, Gachibowli, Secunderabad, Masab Tank, Khairtabad, Female):
  if Discount_offered <= 10.5:
    if Prior_purchases <= 2.5:
      if Rating_of_customer <= 3.5:
        if Weight_of_food_in_gms <= 4025.0:
          return [[23. 78.]]
        else:  # if Weight_of_food_in_gms > 4025.0
          return [[428. 289.]]
      else:  # if Rating_of_customer > 3.5
        return [[193. 140.]]
    else:  # if Prior_purchases > 2.5
      if Weight_of_food_in_gms <= 4018.5:
        if Discount_offered <= 5.5:
          if Weight_of_food_in_gms <= 1987.0:
            if Calls_to_customer_care <= 3.5:
              if Cost_of_food <= 264.75:
                return [[ 4. 30.]]
              else:  # if Cost_of_food > 264.75
                return [[12.  6.]]
            else:  # if Calls_to_customer_care > 3.5
              return [[327. 346.]]
          else:  # if Weight_of_food_in_gms > 1987.0
            if Weight_of_food_in_gms <= 3999.0:
              return [[ 1. 83.]]
            else:  # if Weight_of_food_in_gms > 3999.0
              return [[8. 8.]]
        else:  # if Discount_offered > 5.5
          if Cost_of_food <= 321.0:
            return [[ 16. 105.]]
          else:  # if Cost_of_food > 321.0
            if Weight_of_food_in_gms <= 2063.0:
              return [[372. 306.]]
            else:  # if Weight_of_food_in_gms > 2063.0
              return [[ 2. 42.]]
      else:  # if Weight_of_food_in_gms > 4018.5
        return [[1860. 1415.]]
  else:  # if Discount_offered > 10.5
    return [[   0. 1849.]]
```

**Restaurant can use above rules to find out when they can deliver on time and what parameters they can tweak to give maximum on-time delivery**