In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import warnings
warnings.filterwarnings("ignore")

In [3]:
train_df = pd.read_csv("zion_training_data.csv")
train_df.head()

ID      Location Mode_of_delivery  Calls_to_customer_care  \
0   1    Gachibowli             Auto                       4   
1   2   Hitech City             Auto                       4   
2   3  Secunderabad             Auto                       2   
3   4    Khairtabad             Auto                       3   
4   5    Masab Tank             Auto                       2   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0                 2.0         265.5              3.0                  F   
1                 5.0         324.0              2.0                  M   
2                 2.0         274.5              4.0                  M   
3                 3.0         264.0              4.0                  M   
4                 NaN         276.0              NaN                  F   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0                44                   1233                1  
1                59                   3088                1  
2                48                   3374                1  
3                10                   1177                1  
4                46                   2484                1

In [4]:
train_df.describe()

ID  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
count   8249.000000             8249.000000         6177.000000   8249.000000   
mean    5479.967632                4.040975            3.011332    314.937811   
std     3173.300627                1.138140            1.415198     71.890029   
min        1.000000                2.000000            1.000000    144.000000   
25%     2740.000000                3.000000            2.000000    253.500000   
50%     5486.000000                4.000000            3.000000    321.000000   
75%     8213.000000                5.000000            4.000000    376.500000   
max    10999.000000                7.000000            5.000000    465.000000   

       Prior_purchases  Discount_offered  Weight_of_food_in_gms  \
count      7004.000000       8249.000000            8249.000000   
mean          3.570817         13.433022            3641.897442   
std           1.524135         16.236907            1636.962861   
min           2.000000          1.000000            1001.000000   
25%           3.000000          4.000000            1841.000000   
50%           3.000000          7.000000            4152.000000   
75%           4.000000         10.000000            5065.000000   
max          10.000000         65.000000            7846.000000   

       Reached_on_time  
count       8249.00000  
mean           0.59680  
std            0.49057  
min            0.00000  
25%            0.00000  
50%            1.00000  
75%            1.00000  
max            1.00000

In [5]:
test_df = pd.read_csv("zion_testing_data.csv")
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2750 non-null   int64  
 1   Location                2750 non-null   object 
 2   Mode_of_delivery        2750 non-null   object 
 3   Calls_to_customer_care  2750 non-null   int64  
 4   Rating_of_customer      2072 non-null   float64
 5   Cost_of_food            2750 non-null   float64
 6   Prior_purchases         2345 non-null   float64
 7   Gender_of_customer      2750 non-null   object 
 8   Discount_offered        2750 non-null   int64  
 9   Weight_of_food_in_gms   2750 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 215.0+ KB


EDA

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8249 entries, 0 to 8248
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      8249 non-null   int64  
 1   Location                8249 non-null   object 
 2   Mode_of_delivery        8249 non-null   object 
 3   Calls_to_customer_care  8249 non-null   int64  
 4   Rating_of_customer      6177 non-null   float64
 5   Cost_of_food            8249 non-null   float64
 6   Prior_purchases         7004 non-null   float64
 7   Gender_of_customer      8249 non-null   object 
 8   Discount_offered        8249 non-null   int64  
 9   Weight_of_food_in_gms   8249 non-null   int64  
 10  Reached_on_time         8249 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 709.0+ KB


In [7]:
train_df.Location.value_counts() # one-hot encoding

Hitech City     2725
Gachibowli      1397
Secunderabad    1389
Masab Tank      1375
Khairtabad      1363
Name: Location, dtype: int64

In [8]:
train_df.Mode_of_delivery.value_counts() # doing label encoding since bike is faster than auto and auto is faster than car

Bike    5591
Car     1332
Auto    1326
Name: Mode_of_delivery, dtype: int64

In [9]:
train_df.Calls_to_customer_care.describe() # remove outliers

count    8249.000000
mean        4.040975
std         1.138140
min         2.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Calls_to_customer_care, dtype: float64

In [10]:
train_df.Rating_of_customer.describe() # remove outliers; fill missing value using median and then using model based

count    6177.000000
mean        3.011332
std         1.415198
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Rating_of_customer, dtype: float64

In [11]:
train_df.Cost_of_food.describe() # remove outliers;

count    8249.000000
mean      314.937811
std        71.890029
min       144.000000
25%       253.500000
50%       321.000000
75%       376.500000
max       465.000000
Name: Cost_of_food, dtype: float64

In [12]:
train_df.Prior_purchases.describe() # remove outliers; fill missing value using median and then using model based

count    7004.000000
mean        3.570817
std         1.524135
min         2.000000
25%         3.000000
50%         3.000000
75%         4.000000
max        10.000000
Name: Prior_purchases, dtype: float64

In [13]:
train_df.Gender_of_customer.value_counts()

F    4138
M    4111
Name: Gender_of_customer, dtype: int64

In [14]:
train_df.Discount_offered.describe() # remove outliers;

count    8249.000000
mean       13.433022
std        16.236907
min         1.000000
25%         4.000000
50%         7.000000
75%        10.000000
max        65.000000
Name: Discount_offered, dtype: float64

In [15]:

train_df.Weight_of_food_in_gms.describe() # remove outliers;

count    8249.000000
mean     3641.897442
std      1636.962861
min      1001.000000
25%      1841.000000
50%      4152.000000
75%      5065.000000
max      7846.000000
Name: Weight_of_food_in_gms, dtype: float64

In [16]:
train_df.Reached_on_time.value_counts()

1    4923
0    3326
Name: Reached_on_time, dtype: int64

**Handling missing values**

In [17]:
# Rating_of_customer, Prior_purchases
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8249 entries, 0 to 8248
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      8249 non-null   int64  
 1   Location                8249 non-null   object 
 2   Mode_of_delivery        8249 non-null   object 
 3   Calls_to_customer_care  8249 non-null   int64  
 4   Rating_of_customer      6177 non-null   float64
 5   Cost_of_food            8249 non-null   float64
 6   Prior_purchases         7004 non-null   float64
 7   Gender_of_customer      8249 non-null   object 
 8   Discount_offered        8249 non-null   int64  
 9   Weight_of_food_in_gms   8249 non-null   int64  
 10  Reached_on_time         8249 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 709.0+ KB


In [18]:
missing_cols_matadata = train_df[['Rating_of_customer', 'Prior_purchases']].median()
train_df[['Rating_of_customer', 'Prior_purchases']] = train_df[['Rating_of_customer', 'Prior_purchases']].fillna(missing_cols_matadata)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8249 entries, 0 to 8248
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      8249 non-null   int64  
 1   Location                8249 non-null   object 
 2   Mode_of_delivery        8249 non-null   object 
 3   Calls_to_customer_care  8249 non-null   int64  
 4   Rating_of_customer      8249 non-null   float64
 5   Cost_of_food            8249 non-null   float64
 6   Prior_purchases         8249 non-null   float64
 7   Gender_of_customer      8249 non-null   object 
 8   Discount_offered        8249 non-null   int64  
 9   Weight_of_food_in_gms   8249 non-null   int64  
 10  Reached_on_time         8249 non-null   int64  
dtypes: float64(3), int64(5), object(3)
memory usage: 709.0+ KB


Handling Categories

In [19]:
train_df['Mode_of_delivery'] = train_df.Mode_of_delivery.replace({'Bike': 3, 'Auto':2, 'Car':1}) 
train_df['Mode_of_delivery'].value_counts()

3    5591
1    1332
2    1326
Name: Mode_of_delivery, dtype: int64

**Handling Numerical**

In [20]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8249 entries, 0 to 8248
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      8249 non-null   int64  
 1   Location                8249 non-null   object 
 2   Mode_of_delivery        8249 non-null   int64  
 3   Calls_to_customer_care  8249 non-null   int64  
 4   Rating_of_customer      8249 non-null   float64
 5   Cost_of_food            8249 non-null   float64
 6   Prior_purchases         8249 non-null   float64
 7   Gender_of_customer      8249 non-null   object 
 8   Discount_offered        8249 non-null   int64  
 9   Weight_of_food_in_gms   8249 non-null   int64  
 10  Reached_on_time         8249 non-null   int64  
dtypes: float64(3), int64(6), object(2)
memory usage: 709.0+ KB


In [21]:
num_feat = ['Mode_of_delivery', 'Calls_to_customer_care', 'Rating_of_customer', 'Cost_of_food', 'Prior_purchases', 'Discount_offered', 'Weight_of_food_in_gms']


In [22]:
# train_df = train_df_orig
train_df.head(1)

ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0   1  Gachibowli                 2                       4   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0                 2.0         265.5              3.0                  F   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0                44                   1233                1

In [23]:
# remove outliers
from scipy import stats
print(train_df.shape)
train_df_orig = train_df.copy()
train_df = train_df[(np.abs(stats.zscore(train_df[num_feat])) < 3).all(axis=1)]
print(train_df.shape)

(8249, 11)
(7943, 11)


In [24]:
enc = OneHotEncoder(handle_unknown='ignore', drop = 'first')
cat_cols = ['Location', 'Gender_of_customer']

enc.fit(train_df[cat_cols])
print(enc.categories_)

cat_feat = enc.transform(train_df[cat_cols]).toarray()
print(cat_feat)

cat_df = pd.DataFrame(cat_feat)
print(cat_df.shape)
cat_df.head(1)

[array(['Gachibowli', 'Hitech City', 'Khairtabad', 'Masab Tank',
       'Secunderabad'], dtype=object), array(['F', 'M'], dtype=object)]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 ...
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
(7943, 5)


0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0

In [25]:
train_df[num_feat].describe()

Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  \
count       7943.000000             7943.000000         7943.000000   
mean           2.514289                4.051240            3.007050   
std            0.757746                1.142798            1.222512   
min            1.000000                2.000000            1.000000   
25%            2.000000                3.000000            2.000000   
50%            3.000000                4.000000            3.000000   
75%            3.000000                5.000000            4.000000   
max            3.000000                7.000000            5.000000   

       Cost_of_food  Prior_purchases  Discount_offered  Weight_of_food_in_gms  
count   7943.000000       7943.00000       7943.000000            7943.000000  
mean     315.526312          3.34521         12.758404            3646.968148  
std       71.924844          1.10295         15.280494            1641.892742  
min      144.000000          2.00000          1.000000            1001.000000  
25%      255.000000          3.00000          4.000000            1837.000000  
50%      321.000000          3.00000          7.000000            4170.000000  
75%      376.500000          4.00000         10.000000            5071.000000  
max      465.000000          7.00000         62.000000            7846.000000

In [26]:
# scaling
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

train_df[num_feat] = ss.fit_transform(train_df[num_feat])

train_df[num_feat].describe()

Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  \
count      7.943000e+03            7.943000e+03        7.943000e+03   
mean       1.789104e-18            3.864465e-16       -9.929528e-17   
std        1.000063e+00            1.000063e+00        1.000063e+00   
min       -1.998539e+00           -1.795041e+00       -1.641846e+00   
25%       -6.787522e-01           -9.199408e-01       -8.238066e-01   
50%        6.410345e-01           -4.484023e-02       -5.767367e-03   
75%        6.410345e-01            8.302604e-01        8.122719e-01   
max        6.410345e-01            2.580462e+00        1.630311e+00   

       Cost_of_food  Prior_purchases  Discount_offered  Weight_of_food_in_gms  
count  7.943000e+03     7.943000e+03      7.943000e+03           7.943000e+03  
mean  -2.862567e-17    -2.862567e-17     -2.862567e-17          -2.862567e-17  
std    1.000063e+00     1.000063e+00      1.000063e+00           1.000063e+00  
min   -2.384949e+00    -1.219724e+00     -7.695526e-01          -1.611637e+00  
25%   -8.415746e-01    -3.130072e-01     -5.732115e-01          -1.102436e+00  
50%    7.610767e-02    -3.130072e-01     -3.768704e-01           3.185743e-01  
75%    8.477950e-01     5.937092e-01     -1.805293e-01           8.673657e-01  
max    2.078324e+00     3.313858e+00      3.222716e+00           2.557595e+00

In [27]:
print(train_df.shape)
train_df.head(1)

(7943, 11)


ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0   1  Gachibowli         -0.678752                -0.04484   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0           -0.823807      -0.69558        -0.313007                  F   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0           2.04467              -1.470328                1

In [28]:
from sklearn.decomposition import PCA
pca = PCA(n_components=7, svd_solver='full')
pca.fit(train_df[num_feat])
print(pca.explained_variance_ratio_)

[0.24435505 0.19262897 0.14377503 0.14191728 0.11784398 0.09571223
 0.06376746]


In [29]:
print(train_df[num_feat].shape, cat_df.shape)
x_train = pd.concat([train_df[num_feat].reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)
print(x_train.shape)
x_train.head(1)

(7943, 7) (7943, 5)
(7943, 12)


Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
0         -0.678752                -0.04484           -0.823807      -0.69558   

   Prior_purchases  Discount_offered  Weight_of_food_in_gms    0    1    2  \
0        -0.313007           2.04467              -1.470328  0.0  0.0  0.0   

     3    4  
0  0.0  0.0

In [30]:
y_train = train_df.Reached_on_time
print(y_train.shape)

(7943,)


Modelling

When we want to use any model, just run that specific modelling cell one, not the other models.

In [ ]:
# Grid search cross validation
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

parameters = [{'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']},
              {'penalty':['none', 'l2', 'l1', 'elasticnet']},
              {'C':[0.001, 0.01, 0.1, 1, 10, 100]}]



grid_search = GridSearchCV(estimator = logreg,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           verbose=0)


grid_search.fit(x_train, y_train)

print("tuned hpyerparameters :(best parameters) ",grid_search.best_params_)
print("accuracy :",grid_search.best_score_)

tuned hpyerparameters :(best parameters)  {'solver': 'liblinear'}
accuracy : 0.592816086032278


In [ ]:
logreg = LogisticRegression(**grid_search.best_params_)
logreg.fit(x_train, y_train)
logreg

LogisticRegression(solver='liblinear')

SVM

In [ ]:
from sklearn.svm import SVC
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(x_train, y_train)


# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.592 total time=   3.7s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.592 total time=   3.7s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.578 total time=   3.5s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.564 total time=   3.7s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.562 total time=   4.2s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.643 total time=   2.6s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.709 total time=   2.7s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.505 total time=   2.4s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.414 total time=   2.3s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.411 total time=   2.3s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.592 total time=   2.5s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

k_range = list(range(1, 31))
print(k_range)

param_grid = dict(n_neighbors=k_range)
print(param_grid)

knn = knn = KNeighborsClassifier()

grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False)
grid.fit(x_train, y_train)


# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}
{'n_neighbors': 2}
KNeighborsClassifier(n_neighbors=2)


Random Forest

In [ ]:
# Final Model-1: 
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=42)

param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

grid = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5, verbose = 3)
grid.fit(x_train, y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 500}
RandomForestClassifier(max_depth=8, n_estimators=500, random_state=42)


In [31]:
# Final Model-1: 
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(**{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 500}, random_state=42)

rfc.fit(x_train, y_train)

RandomForestClassifier(max_depth=8, n_estimators=500, random_state=42)

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

Decision Tree

In [43]:
# Final Model-2
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : [5, 6, 7, 8, 9],
              'criterion' :['gini', 'entropy']
             }
tree_clas = DecisionTreeClassifier(random_state=1024)
grid = GridSearchCV(estimator=tree_clas, param_grid=param_grid, cv=5, verbose=True)
grid.fit(x_train, y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

Fitting 5 folds for each of 90 candidates, totalling 450 fits
{'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 8, 'max_features': 'auto'}
DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=8,
                       max_features='auto', random_state=1024)


**Submission File**

In [32]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2750 non-null   int64  
 1   Location                2750 non-null   object 
 2   Mode_of_delivery        2750 non-null   object 
 3   Calls_to_customer_care  2750 non-null   int64  
 4   Rating_of_customer      2072 non-null   float64
 5   Cost_of_food            2750 non-null   float64
 6   Prior_purchases         2345 non-null   float64
 7   Gender_of_customer      2750 non-null   object 
 8   Discount_offered        2750 non-null   int64  
 9   Weight_of_food_in_gms   2750 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 215.0+ KB


In [33]:
test_df[['Rating_of_customer', 'Prior_purchases']] = test_df[['Rating_of_customer', 'Prior_purchases']].fillna(missing_cols_matadata)

In [34]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      2750 non-null   int64  
 1   Location                2750 non-null   object 
 2   Mode_of_delivery        2750 non-null   object 
 3   Calls_to_customer_care  2750 non-null   int64  
 4   Rating_of_customer      2750 non-null   float64
 5   Cost_of_food            2750 non-null   float64
 6   Prior_purchases         2750 non-null   float64
 7   Gender_of_customer      2750 non-null   object 
 8   Discount_offered        2750 non-null   int64  
 9   Weight_of_food_in_gms   2750 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 215.0+ KB


In [35]:
print(cat_cols)
print(num_feat)

['Location', 'Gender_of_customer']
['Mode_of_delivery', 'Calls_to_customer_care', 'Rating_of_customer', 'Cost_of_food', 'Prior_purchases', 'Discount_offered', 'Weight_of_food_in_gms']


In [36]:
test_df['Mode_of_delivery'] = test_df.Mode_of_delivery.replace({'Bike': 3, 'Auto':2, 'Car':1}) 
test_df['Mode_of_delivery'].value_counts()

3    1871
2     451
1     428
Name: Mode_of_delivery, dtype: int64

In [37]:
test_df[num_feat] = ss.transform(test_df[num_feat])

In [38]:
cat_feat_test = enc.transform(test_df[cat_cols]).toarray()
print(cat_feat_test)

cat_df_test = pd.DataFrame(cat_feat_test)
print(cat_df_test.shape)
cat_df_test.head(1)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1.]]
(2750, 5)


0    1    2    3    4
0  0.0  0.0  0.0  0.0  1.0

In [39]:
print(test_df[num_feat].shape, cat_df_test.shape)
x_test = pd.concat([test_df[num_feat].reset_index(drop=True), cat_df_test.reset_index(drop=True)], axis=1)
print(x_test.shape)
x_test.head(1)

(2750, 7) (2750, 5)
(2750, 12)


Mode_of_delivery  Calls_to_customer_care  Rating_of_customer  Cost_of_food  \
0         -0.678752                -0.04484           -0.005767     -1.050139   

   Prior_purchases  Discount_offered  Weight_of_food_in_gms    0    1    2  \
0        -0.313007         -0.507764               0.483029  0.0  0.0  0.0   

     3    4  
0  0.0  1.0

In [40]:
test_df['Reached_on_time'] = rfc.predict(x_test).astype('int')
test_df.head(2)

ID    Location  Mode_of_delivery  Calls_to_customer_care  \
0  10273  Gachibowli         -0.678752                -0.04484   
1   3691  Gachibowli         -1.998539                -0.04484   

   Rating_of_customer  Cost_of_food  Prior_purchases Gender_of_customer  \
0           -0.005767     -1.050139        -0.313007                  M   
1            0.812272      0.847795        -0.313007                  F   

   Discount_offered  Weight_of_food_in_gms  Reached_on_time  
0         -0.507764               0.483029                0  
1         -0.507764               1.104302                0

In [41]:
test_df[['ID', 'Reached_on_time']].to_csv("submission_rf.csv", index=False)

**Solution Document**

**Why did I choose the Random Forest model as Final Model?**
- I was getting best cross-validation score and public leader board score, so I chose this model becase it has least generalisation error among the tried models. 
- Random Forest reduced variance from Decision Tree Model which makes it more robust. 
- Logistic regression model was the baseline model and other models were not performing very well on leaderboard.

**Suggestions to Zion Restaurants:**

In [ ]:
from sklearn.tree import _tree

def tree_to_code(tree, feature_names):
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]
    print("def tree({}):".format(", ".join(feature_names)))

    def recurse(node, depth):
        indent = "  " * depth
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            print("{}if {} <= {}:".format(indent, name, threshold))
            recurse(tree_.children_left[node], depth + 1)
            print("{}else:  # if {} > {}".format(indent, name, threshold))
            recurse(tree_.children_right[node], depth + 1)
        else:
            print("{}return {}".format(indent, tree_.value[node]))

    recurse(0, 1)

dt = DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=8,
                       max_features='auto', random_state=1024)


train_df_exp = train_df.copy()
train_df_exp[num_feat] = ss.inverse_transform(train_df_exp[num_feat])
x_train_exp = pd.concat([train_df_exp[num_feat].reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)
x_train_exp = x_train_exp.rename({0: 'Gachibowli', 1:'Secunderabad', 2:'Masab Tank', 3:'Khairtabad', 4:'Female'}, axis=1)

dt.fit(x_train_exp, y_train)
tree_to_code(dt, x_train_exp.columns)

def tree(Mode_of_delivery, Calls_to_customer_care, Rating_of_customer, Cost_of_food, Prior_purchases, Discount_offered, Weight_of_food_in_gms, Gachibowli, Secunderabad, Masab Tank, Khairtabad, Female):
  if Discount_offered <= 10.5:
    if Prior_purchases <= 2.5:
      if Rating_of_customer <= 3.5:
        if Weight_of_food_in_gms <= 4025.0:
          return [[23. 78.]]
        else:  # if Weight_of_food_in_gms > 4025.0
          return [[428. 289.]]
      else:  # if Rating_of_customer > 3.5
        return [[193. 140.]]
    else:  # if Prior_purchases > 2.5
      if Weight_of_food_in_gms <= 4018.5:
        if Discount_offered <= 5.5:
          if Weight_of_food_in_gms <= 1987.0:
            if Calls_to_customer_care <= 3.5:
              if Cost_of_food <= 264.75:
                return [[ 4. 30.]]
              else:  # if Cost_of_food > 264.75
                return [[12.  6.]]
            else:  # if Calls_to_customer_care > 3.5
              return [[327. 346.]]
          else:  #

```python
def tree(Mode_of_delivery, Calls_to_customer_care, Rating_of_customer, Cost_of_food, Prior_purchases, Discount_offered, Weight_of_food_in_gms, Gachibowli, Secunderabad, Masab Tank, Khairtabad, Female):
  if Discount_offered <= 10.5:
    if Prior_purchases <= 2.5:
      if Rating_of_customer <= 3.5:
        if Weight_of_food_in_gms <= 4025.0:
          return [[23. 78.]]
        else:  # if Weight_of_food_in_gms > 4025.0
          return [[428. 289.]]
      else:  # if Rating_of_customer > 3.5
        return [[193. 140.]]
    else:  # if Prior_purchases > 2.5
      if Weight_of_food_in_gms <= 4018.5:
        if Discount_offered <= 5.5:
          if Weight_of_food_in_gms <= 1987.0:
            if Calls_to_customer_care <= 3.5:
              if Cost_of_food <= 264.75:
                return [[ 4. 30.]]
              else:  # if Cost_of_food > 264.75
                return [[12.  6.]]
            else:  # if Calls_to_customer_care > 3.5
              return [[327. 346.]]
          else:  # if Weight_of_food_in_gms > 1987.0
            if Weight_of_food_in_gms <= 3999.0:
              return [[ 1. 83.]]
            else:  # if Weight_of_food_in_gms > 3999.0
              return [[8. 8.]]
        else:  # if Discount_offered > 5.5
          if Cost_of_food <= 321.0:
            return [[ 16. 105.]]
          else:  # if Cost_of_food > 321.0
            if Weight_of_food_in_gms <= 2063.0:
              return [[372. 306.]]
            else:  # if Weight_of_food_in_gms > 2063.0
              return [[ 2. 42.]]
      else:  # if Weight_of_food_in_gms > 4018.5
        return [[1860. 1415.]]
  else:  # if Discount_offered > 10.5
    return [[   0. 1849.]]
```

**Restaurant can use above rules to find out when they can deliver on time and what parameters they can tweak to give maximum on-time delivery**